### ISSUE TITLE
Unable to Install Cocoapod

### ISSUE THREAD

**Issue by cmcgheit** [younatics/ExpandableCell#10]
I am getting a "Unable to find a specification for 'ExpandableCell' When I try to install the Cocoapod?

![screen shot 2017-09-12 at 11 12 20 am](https://user-images.githubusercontent.com/24944725/30336634-66fa395c-97ab-11e7-879b-eac893ab825b.png)

I'm using:
![screen shot 2017-09-12 at 11 14 06 am](https://user-images.githubusercontent.com/24944725/30336671-85115bf0-97ab-11e7-815e-7d94e8c09392.png)

I've tried a handful of times

**Comment by younatics** [comment]
Did you try `pod repo update`?
