### ISSUE TITLE
When I expand the cell then it crashes if one cell is already expended in the following method.

### ISSUE THREAD

**Issue by Pinturaj** [younatics/ExpandableCell#25]
Some time it crashes because  filteredExpandedDatas having no object at that time.

func indexPathsWhere(indexPath: IndexPath) -> [IndexPath] {
        let filteredExpandedDatas = expandableDatas.filter({ (expandedData: ExpandableData) -> Bool in
            return (expandedData.indexPath == indexPath)
        })
        if filteredExpandedDatas.count > 1 {
            fatalError("Something Wrong")
        }
        return filteredExpandedDatas[0].expandedIndexPaths
    }

**Comment by huntergray11** [comment]
I am having the same problem, have you found a fix for this? @Pinturaj

**Comment by younatics** [comment]
Please check latest version. Thanks!

**Comment by Y2JChamp** [comment]
hi, i'm having a similar problem... indexPath is taking count of the expanded rows in the didSelectRowAt method

**Comment by codobuxsocial** [comment]
Facing the same issue, any update on this?

**Comment by tadeha** [comment]
Does anyone know the fix?
