### ISSUE TITLE
Need to expand only One cell at a time.

### ISSUE THREAD

**Issue by asrivastava15** [younatics/ExpandableCell#34]
Is there a way that i could should only one expended cell in table.
Ex: 
Let say User selected Cell A it's expended but when User select Cell B, cell A should close and B open automatically.

**Comment by Sunnymous** [comment]
@asrivastava15 Maybe you can use the bug that is being discussed here : #33

**Comment by yasirmturk** [comment]
"Use the Bug" 👍:) #lol #lmao

**Comment by pikaboo** [comment]
This was fixed in one of the recent changes. Use tableView.expandStyle = .single
