### ISSUE TITLE
Arrow issue

### ISSUE THREAD

**Issue by FaridHaddad** [younatics/ExpandableCell#35]
Hello, when the tableview becomes bigger than the view itself and there are expandable cells down not visible, their arrow gets affected depending of the visible one. So if i open 3 cells,  their arrow is up. When i scroll down and see the fourth cell, its arrow will be as if it was open, but actually it is not.

How do i solve this issue ?

Thanks

**Comment by hemangshah** [comment]
Hi @FaridHaddad , did you fix this issue? I couldn't reproduce this issue at my end. Please feel free to reopen this with your updates.
