### ISSUE TITLE
tableviewcell not using set constraints

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [younatics/ExpandableCell#4]
Hi @younatics ,

This library is cool, I want to use it in one of my applications. But I have issue in rendering the tableviewcell. I manage to use a custom tableviewcell but the problem is the constraints I set in the cell is I think overwritten.

Please see screenshot below.

Storyboard cell with costraints.

<img width="256" alt="screen shot 2017-08-12 at 11 23 59 am" src="https://user-images.githubusercontent.com/5118009/29237461-da5c7a2c-7f50-11e7-8766-539fba4ded0b.png">

Actual result.

<img width="432" alt="screen shot 2017-08-12 at 11 24 11 am" src="https://user-images.githubusercontent.com/5118009/29237462-dcfe58ae-7f50-11e7-9dec-0a58689c4051.png">

Hoping for your response.

Thank you.

**Comment by rjjohnpatrickcruz** [comment]
Hello, hoping to any one that can help me.

Thank you so much!

**Comment by kohdesmond** [comment]
@rjjohnpatrickcruz u might wanna create your own tableviewcell so it will fix the constraints

**Comment by rjjohnpatrickcruz** [comment]
Thanks man, I already fix my issue. Cheers!
