### ISSUE TITLE
In expanded cells, 'SELECTED' mode 'ON' for multiple cells

### ISSUE THREAD

**Issue by mustafiz012** [younatics/ExpandableCell#56]
If I select a expanded cell, it's perfectly alright. But when I go for another selection, both selected cells are being highlighted. So more than one item selection makes this issue. Please let me know if it already has a solution or any way around?

**Comment by pikaboo** [comment]
can you post a screenshot of what you mean ?

**Comment by mustafiz012** [comment]
> can you post a screenshot of what you mean ?

![issue_screenshot](https://user-images.githubusercontent.com/8912593/48477519-03843080-e82c-11e8-9062-6690da2aa8b7.png)

Take a look :: multiple menu items got selected at a time

**Comment by mustafiz012** [comment]
@pikaboo Did you get some times to check it out? I've implemented it and facing this issue. :(

**Comment by pikaboo** [comment]
@mustafiz012 can you share the setup code for your tableview please?

**Comment by mustafiz012** [comment]
You can check [https://github.com/younatics/ExpandableCell/tree/master/ExpandableCellDemo](url) this example. This demo shows same behavior (my issue with).

TableView behavior should be like, when you select a cell (table item) that one should be highlighted (suppose, yellow colored items here).

**Comment by mustafiz012** [comment]
@pikaboo If you please show me the single selected highlighted item??

NB: In the demo, selected item isn't keeping itself highlighted when you click on an item.

![img_20181118_123309__01](https://user-images.githubusercontent.com/8912593/48669413-5a408180-eb2e-11e8-9a06-ee29ada6e69a.jpg)

**Comment by mustafiz012** [comment]
![image](https://user-images.githubusercontent.com/8912593/48669463-40536e80-eb2f-11e8-844b-a70557a767a7.png)

If you uncomment these lines then you'll find the output like my first picture, otherwise selected item acts like, blinking once and disappear the highlighted color

**Comment by pikaboo** [comment]
is this what you were looking for ? 
https://imgur.com/rHDnskM

**Comment by mustafiz012** [comment]
@pikaboo Yes exactly I'm looking for this behavior. Please help me out.

**Comment by pikaboo** [comment]
because i am not able to make new version of the pod, update your podfile with this line:
`pod 'ExpandableCell', :git => 'https://github.com/younatics/ExpandableCell.git', :branch => 'master'
`
And you would need to override your ExpandableCell's method

`isSelectable()`

to keep the expanding cell selected

**Comment by mustafiz012** [comment]
I'll try it and give you feedback. Thanks in advance, hope it's gonna work 👍

**Comment by mustafiz012** [comment]
That's absolutely correct that you should maintain default behavior. But as it's a customized library, you guys please keep user choice (Like I choose it :) ) option. Thanks.

**Comment by pikaboo** [comment]
was your problem solved? I want to close this issue

**Comment by mustafiz012** [comment]
I'm just working on this. One line (expandableTableView.autoRemoveSelection == false) didn't resolve my issue but I've noticed that demo project working fine. So as soon as I figure out my issue, I'm gonna let you know. Thanks.

**Comment by pikaboo** [comment]
the expandable cells themselves also need to be marked as selectable, if you want them to be selectable, otherwise they'll blink and open/close their expansion

**Comment by pikaboo** [comment]
@younatics please update pod version
