### ISSUE TITLE
Wrapper for tableView:willDisplayCell:forRowAtIndexPath:

### ISSUE THREAD

**Issue by ezefranca** [younatics/ExpandableCell#6]
In some implementations use willDisplayCell helps do a more smoothly list. 

What do you thing?

Referece: https://developer.apple.com/documentation/uikit/uitableviewdelegate/1614883-tableview

* opening issue to work before :)

**Comment by ezefranca** [comment]
#7

**Comment by younatics** [comment]
Thanks!
