### ISSUE TITLE
Error:  Cell become white when scroll Table View

### ISSUE THREAD

**Issue by huynh-dat-mulodo** [younatics/ExpandableCell#67]

**Comment by Isuru-Nanayakkara** [comment]
I'm seeing this issue too. Were you able to find a fix?

**Comment by Dipenchudasama** [comment]
I have same issue.. can you please help me?

**Comment by AmrAbedal** [comment]
I have  this issue too , here is a video 
https://drive.google.com/file/d/1z-g4cZ0Euo-jL1BQ_xv37-FUK-4-eZU3/view?usp=sharing
