### ISSUE TITLE
Wrong indexPath in didSelectExpandedRowAt delegate

### ISSUE THREAD

**Issue by codobuxsocial** [younatics/ExpandableCell#74]
Thanks a lot first of all for the awesome library but the indexPath I am getting in expanded cell is of row, the required indexPath in this delegate should start from 0 only then I can get correct value from array of subcategory instead it counts the expanded cell as a row which is not right. Below is my struct, everything works well except the indexPaths are messed up in the expanded cells, please fix. I might be doing something wrong too if that's the case let me know. Thanks!

Also made a video showing wrong indexPath : https://drive.google.com/open?id=10eJUTJSna282Lr_njvcQUAEpG0q7bx3_

The class file can be found here : https://drive.google.com/open?id=1iJfZGFFqK4oLvcIeMqcBZVSLXPkdAy2S

```
struct MenuItems{
    
    var sectionName:String
    var data:[SideMenuItems]
    
    var numberOfItems: Int {
        return data.count
    }
    
    subscript(index: Int) -> SideMenuItems {
        return data[index]
    }
    
}

struct SideMenuItems{
    
    var name:String
    var image:UIImage
    var subCategoryItems:[SubCategoryItems]?
    
    init(name:String,image:UIImage,subCategoryItems:[SubCategoryItems]) {
        self.name = name
        self.image = image
        self.subCategoryItems = subCategoryItems
    }
    
}

struct SubCategoryItems {
    let subCat: String?
    
    init(subCat: String) {
        self.subCat = subCat
    }
}

```

**Comment by tadeha** [comment]
@codobuxsocial How did you fix the issue?

**Comment by codobuxsocial** [comment]
@tadeha i made the Subcategory items custom by taking tableview inside cell and changing its height depending on elements in array.
