### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by fedorpashin** [younatics/ExpandableCell#77]
Started getting this error after pod install:

> Multiple commands produce '/Users/fedor/Library/Developer/Xcode/DerivedData/...-bgbdsrxqedljvpcbxvkmpclubaes/Build/Products/Debug-iphoneos/.../Assets.car':
> 1) Target '...' (project '...') has compile command with input '/Users/fedor/.../.../.../Assets.xcassets'
> 2) That command depends on command in Target '...' (project '...'): script phase “[CP] Copy Pods Resources”

There are also two warnings:

1. > duplicate output file '/Users/fedor/Library/Developer/Xcode/DerivedData/...-bgbdsrxqedljvpcbxvkmpclubaes/Build/Products/Debug-iphoneos/.../Assets.car' on task: PhaseScriptExecution [CP] Copy Pods Resources /Users/fedor/Library/Developer/Xcode/DerivedData/...-bgbdsrxqedljvpcbxvkmpclubaes/Build/Intermediates.noindex/.../Debug-iphoneos/.../Script-626E2A68364D360141E2BEDF.sh
2. > The app icon set name "AppIcon" is used by multiple app icon sets.

The second one is related to the GoogleMaps pod.

Pod version: **1.3.0.**
Swift version: **5.1.**
Xcode version: **11.3.1.**

**Comment by artemmihelson** [comment]
Have the same error. Seems podspec needs to be corrected:

instead of deprecated `resources` need to use `resource_bundles `

**Comment by artemmihelson** [comment]
@fedorpashin Hi, have updated the Podspec, should be fixed in 1.3.1 version of this pod
